apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: my-java-app
          image: "davidhtcmail/banner-java:v3"  # Replace with your actual image name
          ports:
            - containerPort: 8081
          #:
          #  - name: JAVA_OPTS
           #   value: "-Xms512m -Xmx1024m"  # Adjust JVM options as needed


